--- 
title: "Diario Temtiano edición 20.09.2021"
date: "2021-09-20"
lang: es-es
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
github-repo: temtiteamo/diariotemtiano20092021
description: "Mucho texto acerca de un tramo de la historia temtiana."
header-includes:
  - \usepackage{fancyhdr}
  - \usepackage{lipsum}
  - \pagestyle{plain}
  - \fancyhead[CO,CE]{\thepage}
  - \fancyfoot[LE,RO]{\thepage}
---


# Notas de la edición {-}

**Diario Temtiano** edición 20.09.2021

## Novedades en esta edición {-}

- Añadidos dos nuevos subcapítulos al Sexto capítulo: *Sobre el insondable límite (Sexto capítulo, subcapítulo VI)* y *En continuidad con el desvanecimiento (Sexto capítulo, subcapítulo VII)*, ambos acerca del *//Ya volvemos//*.

- Realizadas pequeñas correcciones en el contenido de unos pocos subcapítulos de la obra, además de los títulos de varios de ellos.

- Explicitado mejor el cambio estético que hubo con la llegada del golpe de estado a Temti, el que la transformó en Itmet, en el siguiente subcapítulo: *El derrocamiento anónimo (Segundo capítulo, subcapítulo IX)*. Además, contemplada la posible aparición de los psíquicos con su poder antes de ese momento, en ese mismo subcapítulo, y en *El retorno de las invasiones escandalosas (Segundo capítulo, subcapítulo X)*.

- Añadida una mención de la vez que se deshabilitó la creación de tems luego de que cerrara Moxxed y Tzzubit un mismo día, al subcapítulo *El retorno de las invasiones escandalosas (Segundo capítulo, subcapítulo X)*.

- Incluida una mención al apagón previo a un cierre de la página, momento durante el cual no se veía ninguna imagen en la home de Temti, en el subcapítulo *Incomunicados entre rozzados (Segundo capítulo, subcapítulo XXI)*.



## Cambios previstos para la próxima edición {-}

- Seguir poniéndose al día.

- Continuar corrigiendo errores.
